### PR TITLE
Disable verify peer for now

### PR DESCRIPTION
**Pull request by asuahsahua**

### CODE REVIEW

**Comment by ksmiley** [comment]
👍

**Comment by Workman** [comment]
👍  -- Makes sense after looking at [the docs](http://php.net/manual/en/context.ssl.php)

**Comment by ccornutt** [comment]
ಠ_ಠ

**Comment by naterator** [comment]
donotwant

**Comment by ksmiley** [comment]
Wassup, Nate. Did you grow a mustache? It looks good.

**Comment by mlockhart** [comment]
🙈

**Pull request closed without merging**
